### ISSUE TITLE
Serverinfowindow error

### ISSUE THREAD

**Issue by ycoskun41** [sLimLong/Info-Panel-Server#1]
Hello
What is the reason?

![image](https://github.com/sLimLong/Info-Panel-Server/assets/83180501/9bc86f3d-57a4-450a-b2a6-11e402b44f60)

**Comment by sLimLong** [comment]
did you link the pictures correctly?

**Comment by ycoskun41** [comment]
I didn't edit at all. I just installed mods.

**Comment by ycoskun41** [comment]
I don't have my computer with me. I will share information when I edit
