### ISSUE TITLE
only 4 image links

### ISSUE THREAD

**Issue by Nixilicous** [sLimLong/Info-Panel-Server#2]
when adding the image links;

<rect name="link1" width="150" height="150" pos="625,-340" pivot="center">
<button pivot="center" sprite="" sound="" controller="ServerInfo">
<label name="ServerDescription" />
<label depth="10" pos="-100,90" width="300" height="300" name="ServerWebsiteURL" text_key="link1url" justify="center" style="press" color="0,0,0,1" font_size="300" upper_case="false" button_name="link1hover"/>
</button>
<texture depth="9" pivot="center" texture="@website image link"/>

i have 4 that work perfectly, but when adding a 5th the game crashes on server initialization, all links etc are correctly set up in localization .

is this a known issue? or is it that 4 is the limit?

if its not normal how would it be fixed?

**Comment by sLimLong** [comment]
There are no problems with 5 pictures

**Comment by Nixilicous** [comment]
turned out that i had the typo in the coding :) all good, had "fun" with the images and getting them to be where i wanted along with the link boarder, but all good now :)
